//  Copyright © 2015-2022 Pico Technology Co., Ltd. All Rights Reserved.

#ifndef PXR_AUDIO_SPATIALIZER_CHANNEL_CONFIG_H
#define PXR_AUDIO_SPATIALIZER_CHANNEL_CONFIG_H

#include <cstdlib>

/**
 * For YGGDRASIL_SURROUND, supported mask are:
 *
 * YGGDRASIL_SURROUND_SETUP_MONO
 * YGGDRASIL_SURROUND_SETUP_STEREO
 * YGGDRASIL_SURROUND_SETUP_2_1
 * YGGDRASIL_SURROUND_SETUP_3_0
 * YGGDRASIL_SURROUND_SETUP_4_0
 * YGGDRASIL_SURROUND_SETUP_QUAD
 * YGGDRASIL_SURROUND_SETUP_3_1
 * YGGDRASIL_SURROUND_SETUP_5_0
 * YGGDRASIL_SURROUND_SETUP_5_0_SIDE
 * YGGDRASIL_SURROUND_SETUP_5_1
 * YGGDRASIL_SURROUND_SETUP_5_1_SIDE
 * YGGDRASIL_SURROUND_SETUP_7_0
 * YGGDRASIL_SURROUND_SETUP_7_1
 * YGGDRASIL_SURROUND_SETUP_5_1_2
 * YGGDRASIL_SURROUND_SETUP_5_1_4
 * YGGDRASIL_SURROUND_SETUP_7_1_2
 * YGGDRASIL_SURROUND_SETUP_7_1_4
 *
 * Further refer to https://trac.ffmpeg.org/wiki/AudioChannelManipulation
 *
 * For YGGDRASIL_AMBIX and YGGDRASIL_AMBIX_WITH_HEADLOCK, supported mask are:
 *
 * YGGDRASIL_AMBIX_ORDER_1
 * YGGDRASIL_AMBIX_ORDER_2
 * YGGDRASIL_AMBIX_ORDER_3
 * YGGDRASIL_AMBIX_ORDER_4
 * YGGDRASIL_AMBIX_ORDER_5
 * YGGDRASIL_AMBIX_ORDER_6
 * YGGDRASIL_AMBIX_ORDER_7
 *
 * For YGGDRASIL_FUMA, supported mask are:
 *
 * YGGDRASIL_FUMA_ORDER_1
 *
 * For YGGDRASIL_TBE, supported mask are:
 *
 * YGGDRASIL_TBE_8
 * YGGDRASIL_TBE_8_2
 *
 */
typedef enum {
    PASP_SURROUND = 0,
    PASP_AMBIX = 1,
    PASP_AMBIX_WITH_HEADLOCK = 2,
    PASP_FUMA = 3,
    PASP_TBE = 4,
} PxrAudioSpatializer_ChannelConfig;

typedef uint32_t PxrAudioSpatializer_ChannelMask;

/// Pico Spatial Audio Surround Channel Mask
/// Pico Spatial Audio Surround Channel Mask - Speakers
#define PASP_SURROUND_FRONT_LEFT 0x1
#define PASP_SURROUND_FRONT_RIGHT 0x2
#define PASP_SURROUND_FRONT_CENTER 0x4
#define PASP_SURROUND_LOW_FREQUENCY 0x8
#define PASP_SURROUND_BACK_LEFT 0x10
#define PASP_SURROUND_BACK_RIGHT 0x20
#define PASP_SURROUND_SIDE_LEFT 0x40
#define PASP_SURROUND_SIDE_RIGHT 0x80
#define PASP_SURROUND_TOP_FRONT_LEFT 0x100
#define PASP_SURROUND_TOP_FRONT_RIGHT 0x200
#define PASP_SURROUND_TOP_BACK_LEFT 0x400
#define PASP_SURROUND_TOP_BACK_RIGHT 0x800
#define PASP_SURROUND_BACK_CENTER 0x1000
#define PASP_SURROUND_TOP_SIDE_LEFT 0x2000
#define PASP_SURROUND_TOP_SIDE_RIGHT 0x4000
#define PASP_SURROUND_SIDE_SURROUND (PASP_SURROUND_SIDE_LEFT | PASP_SURROUND_SIDE_RIGHT)
#define PASP_SURROUND_BACK_SURROUND (PASP_SURROUND_BACK_LEFT | PASP_SURROUND_BACK_RIGHT)

/// Pico Spatial Audio Surround Channel Mask - Setup
/// mono = FC
#define PASP_SURROUND_SETUP_MONO PASP_SURROUND_FRONT_CENTER
#define PASP_SURROUND_INDEX_MONO_FC (0)
/// stereo = FL+FR
#define PASP_SURROUND_SETUP_STEREO (PASP_SURROUND_FRONT_LEFT | PASP_SURROUND_FRONT_RIGHT)
#define PASP_SURROUND_INDEX_STEREO_FL (0)
#define PASP_SURROUND_INDEX_STEREO_FR (1)
/// 2.1 = FL+FR+LFE
#define PASP_SURROUND_SETUP_2_1 (PASP_SURROUND_SETUP_STEREO | PASP_SURROUND_LOW_FREQUENCY)
#define PASP_SURROUND_INDEX_2_1_FL (0)
#define PASP_SURROUND_INDEX_2_1_FR (1)
#define PASP_SURROUND_INDEX_2_1_LFE (2)
/// 3.0 = FL+FR+FC
#define PASP_SURROUND_SETUP_3_0 (PASP_SURROUND_SETUP_STEREO | PASP_SURROUND_FRONT_CENTER)
#define PASP_SURROUND_INDEX_3_0_FL (0)
#define PASP_SURROUND_INDEX_3_0_FR (1)
#define PASP_SURROUND_INDEX_3_0_FC (2)
/// 4.0 = FL+FR+FC+BC
#define PASP_SURROUND_SETUP_4_0 (PASP_SURROUND_SETUP_3_0 | PASP_SURROUND_BACK_CENTER)
#define PASP_SURROUND_INDEX_4_0_FL (0)
#define PASP_SURROUND_INDEX_4_0_FR (1)
#define PASP_SURROUND_INDEX_4_0_FC (2)
#define PASP_SURROUND_INDEX_4_0_BC (3)
/// quad = FL+FR+BL+BR
#define PASP_SURROUND_SETUP_QUAD (PASP_SURROUND_SETUP_STEREO | PASP_SURROUND_BACK_SURROUND)
#define PASP_SURROUND_INDEX_QUAD_FL (0)
#define PASP_SURROUND_INDEX_QUAD_FR (1)
#define PASP_SURROUND_INDEX_QUAD_BL (2)
#define PASP_SURROUND_INDEX_QUAD_BR (3)
/// 3.1 = FL+FR+FC+LFE
#define PASP_SURROUND_SETUP_3_1 (PASP_SURROUND_SETUP_3_0 | PASP_SURROUND_LOW_FREQUENCY)
#define PASP_SURROUND_INDEX_3_1_FL (0)
#define PASP_SURROUND_INDEX_3_1_FR (1)
#define PASP_SURROUND_INDEX_3_1_FC (2)
#define PASP_SURROUND_INDEX_3_1_LFE (3)
/// 5.0 = FL+FR+FC+BL+BR
#define PASP_SURROUND_SETUP_5_0 (PASP_SURROUND_SETUP_3_0 | PASP_SURROUND_BACK_SURROUND)
#define PASP_SURROUND_INDEX_5_0_FL (0)
#define PASP_SURROUND_INDEX_5_0_FR (1)
#define PASP_SURROUND_INDEX_5_0_FC (2)
#define PASP_SURROUND_INDEX_5_0_BL (3)
#define PASP_SURROUND_INDEX_5_0_BR (4)
/// 5.0(side) = FL+FR+FC+SL+SR
#define PASP_SURROUND_SETUP_5_0_SIDE (PASP_SURROUND_SETUP_3_0 | PASP_SURROUND_SIDE_SURROUND)
#define PASP_SURROUND_INDEX_5_0_SIDE_FL (0)
#define PASP_SURROUND_INDEX_5_0_SIDE_FR (1)
#define PASP_SURROUND_INDEX_5_0_SIDE_FC (2)
#define PASP_SURROUND_INDEX_5_0_SIDE_SL (3)
#define PASP_SURROUND_INDEX_5_0_SIDE_SR (4)
/// 5.1 = FL+FR+FC+LFE+BL+BR
#define PASP_SURROUND_SETUP_5_1 (PASP_SURROUND_SETUP_3_1 | PASP_SURROUND_BACK_SURROUND)
#define PASP_SURROUND_INDEX_5_1_FL (0)
#define PASP_SURROUND_INDEX_5_1_FR (1)
#define PASP_SURROUND_INDEX_5_1_FC (2)
#define PASP_SURROUND_INDEX_5_1_LFE (3)
#define PASP_SURROUND_INDEX_5_1_BL (4)
#define PASP_SURROUND_INDEX_5_1_BR (5)
/// 5.1(side) = FL+FR+FC+LFE+SL+SR
#define PASP_SURROUND_SETUP_5_1_SIDE (PASP_SURROUND_SETUP_3_1 | PASP_SURROUND_SIDE_SURROUND)
#define PASP_SURROUND_INDEX_5_1_SIDE_FL (0)
#define PASP_SURROUND_INDEX_5_1_SIDE_FR (1)
#define PASP_SURROUND_INDEX_5_1_SIDE_FC (2)
#define PASP_SURROUND_INDEX_5_1_SIDE_LFE (3)
#define PASP_SURROUND_INDEX_5_1_SIDE_SL (4)
#define PASP_SURROUND_INDEX_5_1_SIDE_SR (5)
/// 7.0 = FL+FR+FC+BL+BR+SL+SR
#define PASP_SURROUND_SETUP_7_0 (PASP_SURROUND_SETUP_5_0 | PASP_SURROUND_SIDE_SURROUND)
#define PASP_SURROUND_INDEX_7_0_FL (0)
#define PASP_SURROUND_INDEX_7_0_FR (1)
#define PASP_SURROUND_INDEX_7_0_FC (2)
#define PASP_SURROUND_INDEX_7_0_BL (3)
#define PASP_SURROUND_INDEX_7_0_BR (4)
#define PASP_SURROUND_INDEX_7_0_SL (5)
#define PASP_SURROUND_INDEX_7_0_SR (6)
/// 7.1 = FL+FR+FC+LFE+BL+BR+SL+SR
#define PASP_SURROUND_SETUP_7_1 (PASP_SURROUND_SETUP_5_1 | PASP_SURROUND_SIDE_SURROUND)
#define PASP_SURROUND_INDEX_7_1_FL (0)
#define PASP_SURROUND_INDEX_7_1_FR (1)
#define PASP_SURROUND_INDEX_7_1_FC (2)
#define PASP_SURROUND_INDEX_7_1_LFE (3)
#define PASP_SURROUND_INDEX_7_1_BL (4)
#define PASP_SURROUND_INDEX_7_1_BR (5)
#define PASP_SURROUND_INDEX_7_1_SL (6)
#define PASP_SURROUND_INDEX_7_1_SR (7)
/// 5.1.2 = FL+FR+FC+LFE+BL+BR+TSL+TSR
#define PASP_SURROUND_SETUP_5_1_2 \
    (PASP_SURROUND_SETUP_5_1 | PASP_SURROUND_TOP_SIDE_LEFT | PASP_SURROUND_TOP_SIDE_RIGHT)
#define PASP_SURROUND_INDEX_5_1_2_FL (0)
#define PASP_SURROUND_INDEX_5_1_2_FR (1)
#define PASP_SURROUND_INDEX_5_1_2_FC (2)
#define PASP_SURROUND_INDEX_5_1_2_LFE (3)
#define PASP_SURROUND_INDEX_5_1_2_BL (4)
#define PASP_SURROUND_INDEX_5_1_2_BR (5)
#define PASP_SURROUND_INDEX_5_1_2_TSL (6)
#define PASP_SURROUND_INDEX_5_1_2_TSR (7)
/// 5.1.4 = FL+FR+FC+LFE+BL+BR+TFL+TFR+TBL+TBR
#define PASP_SURROUND_SETUP_5_1_4                                                                       \
    (PASP_SURROUND_SETUP_5_1 | PASP_SURROUND_TOP_FRONT_LEFT | PASP_SURROUND_TOP_FRONT_RIGHT | \
     PASP_SURROUND_TOP_BACK_LEFT | PASP_SURROUND_TOP_BACK_RIGHT)
#define PASP_SURROUND_INDEX_5_1_4_FL (0)
#define PASP_SURROUND_INDEX_5_1_4_FR (1)
#define PASP_SURROUND_INDEX_5_1_4_FC (2)
#define PASP_SURROUND_INDEX_5_1_4_LFE (3)
#define PASP_SURROUND_INDEX_5_1_4_BL (4)
#define PASP_SURROUND_INDEX_5_1_4_BR (5)
#define PASP_SURROUND_INDEX_5_1_4_TFL (6)
#define PASP_SURROUND_INDEX_5_1_4_TFR (7)
#define PASP_SURROUND_INDEX_5_1_4_TBL (8)
#define PASP_SURROUND_INDEX_5_1_4_TBR (9)
/// 7.1.4 = FL+FR+FC+LFE+BL+BR+SL+SR+TSL+TSR
#define PASP_SURROUND_SETUP_7_1_2 \
    (PASP_SURROUND_SETUP_7_1 | PASP_SURROUND_TOP_SIDE_LEFT | PASP_SURROUND_TOP_SIDE_RIGHT)
#define PASP_SURROUND_INDEX_7_1_2_FL (0)
#define PASP_SURROUND_INDEX_7_1_2_FR (1)
#define PASP_SURROUND_INDEX_7_1_2_FC (2)
#define PASP_SURROUND_INDEX_7_1_2_LFE (3)
#define PASP_SURROUND_INDEX_7_1_2_BL (4)
#define PASP_SURROUND_INDEX_7_1_2_BR (5)
#define PASP_SURROUND_INDEX_7_1_2_SL (6)
#define PASP_SURROUND_INDEX_7_1_2_SR (7)
#define PASP_SURROUND_INDEX_7_1_2_TSL (8)
#define PASP_SURROUND_INDEX_7_1_2_TSR (9)
/// 7.1.4 = FL+FR+FC+LFE+BL+BR+SL+SR+TFL+TFR+TBL+TBR
#define PASP_SURROUND_SETUP_7_1_4                                                                       \
    (PASP_SURROUND_SETUP_7_1 | PASP_SURROUND_TOP_FRONT_LEFT | PASP_SURROUND_TOP_FRONT_RIGHT | \
     PASP_SURROUND_TOP_BACK_LEFT | PASP_SURROUND_TOP_BACK_RIGHT)
#define PASP_SURROUND_INDEX_7_1_4_FL (0)
#define PASP_SURROUND_INDEX_7_1_4_FR (1)
#define PASP_SURROUND_INDEX_7_1_4_FC (2)
#define PASP_SURROUND_INDEX_7_1_4_LFE (3)
#define PASP_SURROUND_INDEX_7_1_4_BL (4)
#define PASP_SURROUND_INDEX_7_1_4_BR (5)
#define PASP_SURROUND_INDEX_7_1_4_SL (6)
#define PASP_SURROUND_INDEX_7_1_4_SR (7)
#define PASP_SURROUND_INDEX_7_1_4_TFL (8)
#define PASP_SURROUND_INDEX_7_1_4_TFR (9)
#define PASP_SURROUND_INDEX_7_1_4_TBL (10)
#define PASP_SURROUND_INDEX_7_1_4_TBR (11)

/// Pico Spatial Audio Ambix & AmbixWithHeadlock Channel Mask
#define PASP_AMBIX_ORDER_1 (1)
#define PASP_AMBIX_ORDER_2 (2)
#define PASP_AMBIX_ORDER_3 (3)
#define PASP_AMBIX_ORDER_4 (4)
#define PASP_AMBIX_ORDER_5 (5)
#define PASP_AMBIX_ORDER_6 (6)
#define PASP_AMBIX_ORDER_7 (7)

/// Pico Spatial Audio Fuma Channel Mask
#define PASP_FUMA_ORDER_1 (1)

/// Pico Spatial Audio TBE Channel Mask
#define PASP_TBE_8 (1)
#define PASP_TBE_8_2 (2)

#endif  //  PXR_AUDIO_SPATIALIZER_CHANNEL_CONFIG_H
